---
abstract: ~
author:
  - 'Warachet Samtalee (zdk)'
build_requires:
  Catalyst::Runtime: 5.80015
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
  Test::WWW::Mechanize::Catalyst: 0
  ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Session-State-Auth
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Plugin::Session: 0
  MRO::Compat: 0
  Moose: 0
  MooseX::Emulate::Class::Accessor::Fast: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/zdk/catalyst-plugin-session-state-auth.git
version: 0.0005
